### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by ShaunDreclin** [ksanislo/TitleDB#10]
Would it be possible to add a category selection like "Game", "Application", "Tool"?

**Comment by ksanislo** [comment]
@ShaunDreclin Categories are actually already supported under the /v1 API, however their support isn't fully implemented by FBI. And the main TitleDB web interface is also still stuck on /v0 at the moment itself, as I've not really had any time to do work on this project since January or so.

With any luck, I'll be able to get back to this in the next month or two, and be able to put some more time into interfaces which utilize more of the functionality that already exists in the backend.

**Comment by ShaunDreclin** [comment]
Awesome! 😄
