### ISSUE TITLE
Always keep a local mirror, even for standalone 3dsx/cia files to work around Github dropping TLSv1 support.

### ISSUE THREAD

**Issue by nl255** [ksanislo/TitleDB#16]
Apparently Github is dropping TLSv1 support which means that any 3ds homebrew that uses titledb such as FBI will no longer work with anything that is distributed as standalone cia/3dsx files since those are not mirrored/cached locally on titledb.  An easy way to work around this is to have titledb host all files locally from now on, not just ones from homebrew that is distributed in a compressed format.

**Comment by ksanislo** [comment]
I do actually keep a local mirror of everything, but I’ve been using a 302 redirect offsite to save on bandwidth usage where possible.

Directly switching to a local mirror for everything may or may not be a viable solution though, as the monthly total for data transfer off the site is already quite substantial. I’m going to determine what the state of compressed stream support is in FBI, as I had requested that it be implemented in the switch to the new TitleDB API version some time ago. If I can  enable compressing all .cia content and not just the api we should get a bit more headroom to operate. Otherwise, I’m going to have to find a new hosting provider that will provide more than just a few TB a month at a good rate.

Don’t worry though, the site isn’t going away any time soon, I’ll just have to start getting more creative with what it needs to remain working.
