### ISSUE TITLE
[Suggestion]Sort by date.

### ISSUE THREAD

**Issue by dude8513** [ksanislo/TitleDB#2]
As someone who is pretty much obsessed with homebrew at this point, I really appreciate TitleDB's existence. I think it would be a cool and useful feature to be able to sort titles by date added, so that people like me who are constantly looking for new HB apps can see any new apps as they are added.

**Comment by ksanislo** [comment]
I agree with you completely, and I'm hoping to be able to add support for this when I get to rewriting the user interface application side of things. Unofficially, the backend API provides this information as a set of values for "created_at" and "updated_at", so the data to do what you'd like is actually available right now, it's just a matter of having a UI that can support displaying it as such.

The backend API rewrite is basically stable at this point, so with luck I'll be able to start working on the interface soon. However, It's going to require me learning javascript and modern web development in order to pull it off, so I can't actually make any sort of guarantee on when it will actually get finished, it may still be a few months away. 

Personally, I'm still kind of hoping somebody who knows how to do web-dev work will show up and offer to help with the project. ;)

**Comment by Wolvan** [comment]
Javascript? Why didn't you approach me earlier?

**Comment by ksanislo** [comment]
@Wolvan I thought you already had your hands full with the Homebr3w rewrite. If you want to lend a hand, I'll make a new branch for the UI work when I start on it. Maybe this weekend I'll get started, or at least decide what framework/tools I want to use for it.

**Comment by Wolvan** [comment]
The joke is that I permanently have my hands full but still find time to do shit
