### ISSUE TITLE
App name mismatch in webpage and API.

### ISSUE THREAD

**Issue by PabloMK7** [ksanislo/TitleDB#22]
Hello there, sorry to bother you again.
Recently I have requested the removal of the CTGP-7 installer app that was in titleDB. Today I have added it back as the new installer is fully functional now.

There is a problem tho, for some reason titleDB webpage is showing the proper app name: "CTGP-7" However, the API is showing the old app name "Custom Tracks Grand Prix - 7". This old name is being read by FBI and is installing the 3dsx to the wrong place, messing up the installation process.

**Comment by PabloMK7** [comment]
https://3ds.titledb.com/v1/entry
id: 184

Not sure how it got that description or webpage :/

**Comment by PabloMK7** [comment]
https://3ds.titledb.com/v1/cia
id: 1367 is a duplicate as I messed up with file naming, id: 1369 is the proper one.

id: 768 is a duplicate, id: 770 is the proper one.

Again, sorry for the inconvinence, first time I use titledb.

**Comment by ksanislo** [comment]
@mariohackandglitch First off, I _highly_ recommend that you use some kind of "regular" file hosting service, instead of posting to a bulletin board, as using files attached to posts via titledb isn't well supported at all. It's very hacky and doesn't really follow releases as it would using a more normal host. If you could use GitHub via "releases" there is even better support for maintaining automatic versioning. Alternatively you could name the zip files with a version number such as CTGP-7_installer_1.0.0.zip or similar, incrementing on releases even while using dshack.org as the host and you would get a more functional entry.

Otherwise, can you tell me what you would like changed in here and I'll update it manually:

[https://3ds.titledb.com/v1/entry/184](https://3ds.titledb.com/v1/entry/184) 

And in the full entry with files, you want [CIA #1367](https://3ds.titledb.com/v1/cia/1367) and [TDSX #768](https://3ds.titledb.com/v1/tdsx/768) removed from this:

[https://3ds.titledb.com/v1/entry/184?nested=true](https://3ds.titledb.com/v1/entry/184?nested=true)

Is that correct?

**Comment by PabloMK7** [comment]
Now that you mention it, I have no idea why I'm not using github.

You can delete everything, and I'll resubmit it using the github link.

Just wondering, how can I edit the description, url, etc and which github url do I submit?

**Comment by ksanislo** [comment]
@mariohackandglitch The readme.md file is turned into the description, and the name, author, and headline are used from the GitHub project when an entry is first created. In this case, I think the easiest way to switch it over would be just to put up the files on GitHub and manually re-link the entry to the new source. If you want to make a project, and then upload the zip as a release for it, make sure it's a full release. If you flag it as "pre-release" then TitleDB will skip over it, which allows for public betas without TDB indexing them.

Once you have a release made, you can add it to TDB directly using the link to the .zip from the releases page, but you will still need to let me know the URL here on this issue ticket so I can update the backend to assign it the original entry ID. Otherwise it will be considered a conflicting ID since it comes from a different website than the previous versions and won't be publicly listed.

As I remember, the overall "entry" _should_ update from GitHub automatically after it scans a version tracked release (so, the second release after I've updated the linking), but it is probably easier for me to just update it by hand to what you'd like for the mean-time since its a pre-existing project.

**Comment by PabloMK7** [comment]
Here is the new link.

https://github.com/mariohackandglitch/CTGP-7_Launcher/releases/download/v1.0.0/CTGP-7_installer.zip

Could you set the name to "CTGP-7"? That way FBI will install the 3dsx to SD:/3ds/CTGP-7/CTGP-7.3dsx not SD:/3ds/CTGP-7_Launcher/CTGP-7_Launcher.3dsx"

**Comment by ksanislo** [comment]
@mariohackandglitch How does [the entry](https://3ds.titledb.com/v1/entry/184) look for you now? Anything else you'd like updated or changed in there?

**Comment by PabloMK7** [comment]
Everything looks fine, except for the author, a lot of people made the mod,
people @ dshack.org or dshack.org is better.

Again, thanks a lot! ^^

**Comment by ksanislo** [comment]
@mariohackandglitch No problem, updated to show dshack.org as the author on the entry. Sounds like we're fixed here now, and the site should properly track any new releases made via GitHub within about 15-30 minutes of their release. Let me know if you have any other troubles.
