### ISSUE TITLE
Terraria Invedit

### ISSUE THREAD

**Issue by ghost** [ksanislo/TitleDB#6]
The Terraria Invedit has an invalid URL; the correct download URL is https://github.com/MarcuzD/TerraInveditThreedee/raw/master/TerraInveditThreedee.cia

**Comment by ksanislo** [comment]
It seems like the correct approach here would just be to ask @MarcuzD to make a new GitHub "release". Since this has been found from a previous release's listed files, TDB now expects new releases for versions so it can locate them to be added to the list. Trying to work around this manually is much more complicated than just doing releases properly.

**Comment by SonoSooS** [comment]
[Done.](https://github.com/MarcuzD/TerraInveditThreedee/releases/tag/0.1_C15)

**Comment by ksanislo** [comment]
@MarcuzD TDB will avoid switching to a new version that is marked as "pre-release" since that implies that it's not ready for general distribution. If you'd like this new version to show up, you should remove that flag on the release so it will be detected as the newest valid version.

edit: Manually added the new version so it'll be working immediately. It's still important to not flag pre-release on the next version so it will follow the change automatically.
